version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
      - "/examples/app"
      - "/examples/aurora"
      - "/examples/capacitor"
      - "/examples/flappy-bird"
      - "/examples/pong"
      - "/examples/runtime"
    exclude-paths:
      # Expo SDK: Manually updated with `npx expo install --fix`
      - "examples/react-native"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    open-pull-requests-limit: 1

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 1
