version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
      - "/examples/*"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "@types/node"
    open-pull-requests-limit: 1
