name: CI

on:
  pull_request:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    env:

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Check
        run: npm check

      - name: Format
        run: npm format:check